name: Generate Binary for Windows

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: 😀 build Binary
      run: cargo build --release
    - name: 🎉 save Binary
      uses: actions/upload-artifact@v4
      with:
          name: release
          path: ./target/release/escaperoom.exe
    - name: 📄 add to Release
      uses: softprops/action-gh-release@v2.2.1
      with:
          files: ./target/release/escaperoom.exe
